# Generated by Django 4.0.10 on 2025-01-31 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_edit_books', 'Can edit books')]},
        ),
    ]
