# Generated by Django 4.0.10 on 2025-02-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐☆☆☆☆ (1)'), (2, '⭐⭐☆☆☆ (2)'), (3, '⭐⭐⭐☆☆ (3)'), (4, '⭐⭐⭐⭐☆ (4)'), (5, '⭐⭐⭐⭐⭐ (5)')], default=5),
        ),
    ]
